# Numpy Package

## Function on arrays

The ```numpy``` package, abbreviated ```np``` in programs, provides Python programmers with convenient and powerful functions for creating and manipulating arrays.

For example, the ```diff``` function computes the difference between each adjacent pair of elements in an array. The first element of the ```diff``` is the second element minus the first.

In [4]:
from datascience import *
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [5]:
import numpy as np
np.diff(highs)

array([0.787, 0.198, 0.579])

<img src="NP-1.jpg" width="900" align="center">

<img src="NP-2.jpg" width="900" align="center">

<img src="NP-3.jpg" width="900" align="center">

<img src="NP-4.jpg" width="900" align="center">

# Ranges

A range is an array of numbers in increasing or decreasing order, each separated by a regular interval. Ranges are useful in a surprisingly large number of situations, so it's worthwhile to learn about them.

Ranges are defined using the ```np.arange``` function, which takes either one, two, or three arguments: a start, and end, and a 'step'.

If you pass one argument to ```np.arange```, this becomes the end value, with ```start=0```, ```step=1``` assumed. Two arguments give the ```start``` and ```end``` with ```step=1``` assumed. Three arguments give the ```start```, ```end``` and ```step``` explicitly.

A range always includes its ```start``` value, but does not include its ```end``` value. It counts up by ```step```, and it stops before it gets to the ```end```.

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [8]:
#np.arange(start, end): An array of consecutive increasing integers from start, stopping before end.
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [9]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

When you specify a step, the start, end, and step can all be either positive or negative and may be whole numbers or fractions.

In [10]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

# More on arrays

It's often necessary to compute something that involves data from more than one array. If two arrays are of the same size, Python makes it easy to do calculations involving both arrays.

For our first example, we return once more to the temperature data. This time, we create arrays of average daily high and low temperatures for the decades surrounding 1850, 1900, 1950, and 2000.

In [12]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [13]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728)
lows

array([2.128, 2.371, 2.874, 3.728])

Suppose we'd like to compute the average daily range of temperatures for each decade. That is, we want to subtract the average daily high in the 1850s from the average daily low in the 1850s, and the same for each other decade.

We could write this laboriously using ```.item```:

In [14]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([11.472, 12.016, 11.711, 11.436])

As when we converted an array of temperatures from Celsius to Fahrenheit, Python provides a much cleaner way to write this:

In [15]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

## Elementwise operation on arrays

If an arithmetic operator acts on two arrays of the same size, then the operation is performed on each corresponding pair of elements in the two arrays. The final result is an array.

For example, if ```array1``` and ```array2``` have the same number of elements, then the value of ```array1 * array2``` is an array. Its first element is the first element of ```array1``` times the first element of ```array2```, its second element is the second element of ```array1``` times the second element of ```array2```, and so on.

# Amazing!!! We have completed the Learning Series!!✨✨
<img src="Congratulations.gif" width="700" align="center">